<div id="searchForm"> 
    <h2>Search a specific airline with specific city name (Morning flights)<br /><br /></h2> 
    <?php
    $arrivalflightschedule = new Application_Model_DbTable_Arrivalflightschedule();
    $result = $arrivalflightschedule->airlineList();
    ?>
    Airline
    <select name="arrivalairline" id="arrivalairline">
        <option value="Any Airlines">Any Airlines</option>
        <?php foreach ($result as $value) : ?>   
            <option value="<?=$value['Airline']?>"><?=$value['Airline']?></option>
        <?php endforeach; ?>
    </select>

    <!--input type="text" name="airline01" id="airline01" /-->
    Flight Number <input type="text" name="arrivalflightnumber" id="arrivalflightnumber" />
    <button type="button" id="arrivalflightnumberBtn" style="height: 25px; width: 70px">Filter</button>
</div>

<div id="displayairlineresult">

</div>