<h3>I appreciate any comments and suggestions</h3>
<form name="commentToBeSent" action="/DIAWebZend_Morning/public/index/sentcomment"
      method="post">
    Comment: <br>
    <textarea name="comment" rows="10" cols="80"></textarea>
    <br><br>
    <input type="submit" value="Send" name="send" />
    <input type="reset" value="Reset" name="reset"
           onclick="document.commentToBeSent.comment.focus()" />
</form>
  
<script type="text/javascript">
    document.commentToBeSent.comment.focus()
</script>
