                 
<div id="searchForm"> 
    <h2>Search a specific airline with specific flight number (Morning flights)<br /><br /></h2> 
    <?php
    $departureflightschedule = new Application_Model_DbTable_Departureflightschedule();
    $result = $departureflightschedule->airlineList();
    ?>
    Airline
    <select name="airline" id="airline">
        <option value="Any Airlines">Any Airlines</option>
        <?php foreach ($result as $value) : ?>   
            <option value="<?=$value['Airline']?>"><?=$value['Airline']?></option>
        <?php endforeach; ?>
    </select>

    <!--input type="text" name="airline01" id="airline01" /-->
    Flight Number <input type="text" name="flight" id="flight" />
    <button type="button" id="flightnumberBtn" style="height: 25px; width: 70px">Filter</button>
</div>

<div id="displayairlineresult">

</div>

